/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DappsSlugRouteImport } from './routes/dapps.$slug'
import { Route as BuilderListingsDraftIdStepRouteImport } from './routes/builder_.listings.$draftId.$step'

const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DappsSlugRoute = DappsSlugRouteImport.update({
  id: '/dapps/$slug',
  path: '/dapps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderListingsDraftIdStepRoute =
  BuilderListingsDraftIdStepRouteImport.update({
    id: '/builder_/listings/$draftId/$step',
    path: '/builder/listings/$draftId/$step',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dapps/$slug': typeof DappsSlugRoute
  '/builder/listings/$draftId/$step': typeof BuilderListingsDraftIdStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dapps/$slug': typeof DappsSlugRoute
  '/builder/listings/$draftId/$step': typeof BuilderListingsDraftIdStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dapps/$slug': typeof DappsSlugRoute
  '/builder_/listings/$draftId/$step': typeof BuilderListingsDraftIdStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dapps/$slug'
    | '/builder/listings/$draftId/$step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/dapps/$slug' | '/builder/listings/$draftId/$step'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/dapps/$slug'
    | '/builder_/listings/$draftId/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DappsSlugRoute: typeof DappsSlugRoute
  BuilderListingsDraftIdStepRoute: typeof BuilderListingsDraftIdStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dapps/$slug': {
      id: '/dapps/$slug'
      path: '/dapps/$slug'
      fullPath: '/dapps/$slug'
      preLoaderRoute: typeof DappsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder_/listings/$draftId/$step': {
      id: '/builder_/listings/$draftId/$step'
      path: '/builder/listings/$draftId/$step'
      fullPath: '/builder/listings/$draftId/$step'
      preLoaderRoute: typeof BuilderListingsDraftIdStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DappsSlugRoute: DappsSlugRoute,
  BuilderListingsDraftIdStepRoute: BuilderListingsDraftIdStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
